export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
export const ENCRYPTION_KEY = process.env.NEXT_PUBLIC_ENCRYPTION_SECRET_KEY;
export const STRIPE_PUBLIC_KEY = process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY;
export const FAT_SECRET_BASE_URL = process.env.NEXT_PUBLIC_FAT_SECRET_BASE_URL;
export const FAT_SECRET_CLIENT_ID =
  process.env.NEXT_PUBLIC_FAT_SECRET_CLIENT_ID;
export const FAT_SECRET_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_FAT_SECRET_CLIENT_SECRET;
